project:
  type: website

website:
  title: "Jacob Scott"
  search: false
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wurli
      - icon: mastodon
        href: https://fosstodon.org/@_wurli

format:
  html:
    theme: solar
    monofont: "CommitMono"
    css: styles.css
    filters:
      - filters/show-markdown-syntax.lua

execute:
  freeze: auto
