project:
  type: website

website:
  title: "Jacob Scott"
  search: false
  navbar: false
  sidebar:
    style: "floating"
    contents:
      - about.qmd
      - text: "GitHub"
        icon: github
        href: https://github.com/wurli
      - text: "Mastodon"
        icon: mastodon
        href: https://fosstodon.org/@_wurli

format:
  html:
    theme: solar
    monofont: "CommitMono"
    css: styles.css
    title-block-banner: false
    # toc: true

execute:
  freeze: auto
